# Generated by Django 5.1.5 on 2025-01-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("foto", models.ImageField(upload_to="foto/")),
                ("nome", models.CharField(max_length=150)),
                ("matricula", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Treinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.FileField(upload_to="treinamento/")),
            ],
            options={
                "verbose_name": "Treinamento",
                "verbose_name_plural": "Treinamentos",
            },
        ),
        migrations.CreateModel(
            name="ColetaFaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="roi/")),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaborador_coletas",
                        to="registro.colaborador",
                    ),
                ),
            ],
        ),
    ]
